### ISSUE TITLE
Cannot boot usb drive with linux-4.1-samus

### ISSUE THREAD

**Issue by recri** [raphael/linux-4.1-samus#18]
I've tried to install ubuntu-15.04+linux-4.1-samus on three different usb drives.  In each case, the initial 15.04 install boots, the 15.04 image boots after updating packages, but when the linux-4.1-samus packages have been installed the boot hangs.  

I assume it's something to do with the stripped down config that the samus kernel runs, but I get 7362 lines of diff from comparing config-4.1* to config-3.19.0*.

**Comment by sprc** [comment]
What was the specific error? Did it just eventually time-out waiting for the USB to show up?

The bug below (fixed in 4.2) describes a USB 3.0 bug in the kernel that could explain your issue. It's not clear to me why 3.19 would function though since apparently the bug was introduced in 3.18... unless the 'cherry-pick' tag at the very end means that Canonical applied the 4.2 fix to the Ubuntu-specific kernel and Raphael's package was built against a debian kernel.

https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1455376

**Comment by recri** [comment]
The specific error is that it goes into a loop reading the usb, judging from the rhythmic flashing of some of the drives involved.  I've waited a long time and it hasn't returned to grub once.  But I'll give it 10 minutes and see what happens.

I've hacked the /etc/default/grub on my fourth drive, which is the first usb-3.0 drive I've tried, so I can get to the grub menu.  Starting the explicit linux-4.1-samus boot reports loading linux and loading initial ram disk before going into the loop, allowing the default boot reports nothing and goes into the loop, starting either of the 3.19 images boots fine.

So I've tried with a Toshiba 16GB USB 2.0 thumb drive, a PNY 32GB USB 2.0 thumb drive, a WD 500GB USB 2.0 hard drive, and a SanDisk Extreme 32Gb USB 3.0 thumb drive.  Most were formatted with an ext4 root, one with an ext3 root.

**Comment by recri** [comment]
Okay, the linux-4.1-samus kernel hung up for 20 minutes, it never timed out or dropped back.

In the course of setting up, though, I got the 3.19.0 kernel to also get hung up, so this could be the same bug just manifesting with different frequency.

The symptoms I'm having don't match up with the bug reported to launchpad, except that the kernels do fail to boot through a usb 3.0 port.  The patch from the bug report applied cleanly to the linux-4.1-samus source, only touching one file, so I'll go find a debian/ubuntu kernel construction tutorial and take it for a spin.

**Comment by raphael** [comment]
Let us know if it worked - if it does I'm happy adding the patch to linux-4.1-samus.

**Comment by recri** [comment]
The usb3 hub patch had no effect on the problem, the boot still hangs indefinitely.

**Comment by luv2code** [comment]
My boot hangs as well; but the scenario is different. I've installed Linux Mint 14.2 on the onboard SSD. The computer boots with the default 3.16 kernel and with the [ubuntu mainline 4.1.2](http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.1.2-unstable/) kernel. The touchpad works with the 4.1.2 mainline; but the sound doesn't work of course.

I installed the debs in this repo. select the kernel in the grub, and it prints two lines - one about the kernel being loaded and one about initramfs. Left it there for an hour.

Sorry, I'm new to this kind of trouble shooting; so I'm not sure where to look for clues.

**Comment by recri** [comment]
It's hard to debug code when you don't know which part of it is broken.  I'm just fiddling around with config's trying to turn the ones that boot into the ones that make all the features of the machine work.  If it gets too frustrating, let it be and someone else will sort it out eventually.

**Comment by luv2code** [comment]
I thought maybe it's because I didn't have a swap partition - seems likely that @recri and I would have that in common. So I added one; but it still hangs. I also tried some of the 4.1.0 kernels from earlier tags in this repo; and they hang as well.

**Comment by raphael** [comment]
Have you tried following this? https://wiki.debian.org/InitramfsDebug
Booting in the rescue shell may help identify the issue.
Another thing that wpuld be intersting is to identify config options that are enabled with kernels where booting works vs. options enabled in the linux-4.1-samus kernel (from file `scripts/config`).

**Comment by recri** [comment]
I think I have a fix.  I discovered that the linux-4.1-samus wouldn't run the systemd.bootchart service, so I pulled the most recent generic kernel from http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.1-unstable/ and tuned its config to build an almost generic linux-4.1-samus.  It boots off the thumb drive.  It has touch pad and screen.  It plays "left front" and "right front".  The keyboard back light is lit.  And it makes runs the systemd.bootchart so I can make an svg picture to prove it.

I need to rebuild a few more times to eliminate a hack and s/verbose/quiet/ in my boot command lines, but now I'm going to sleep.

**Comment by recri** [comment]
Forked the repo to build a pull request and found a new source tree for 4.1.2, I should have it built with the new config and uploaded to https://github.com/recri/linux-4.1-samus in a few hours.

**Comment by recri** [comment]
The generic config for linux-4.1-samus is up at https://github.com/recri/linux-4.1-samus built against the 4.1.2 sources.  It takes a good while to compile and my Pixel may need a rest after the several repetitions.  It boots off the SanDisk Extreme USB3 thumb drive and everything appears to work except the touch panel.

**Comment by raphael** [comment]
are the differences only in the config? can you boil down what options made it work?

**Comment by recri** [comment]
The differences are only in the config.  I spent hours trying to tweak your config and ran out of both ideas and energy.  Then I find that apparmor and bootchart are broken by your config, and I start to wonder what else might have accidentally gotten optimized away.  Meanwhile the generic ubuntu kernels are able to boot just fine.  When I was still trying to tweak your config toward the generic, it turned out that you had pushed a lot of things into modules that ubuntu kept built in.

If the kernel happens to work on other machines besides the Pixel, that might be useful; if the kernel is optimized to the Pixel but turns out to have some obscure security flaw because a few options got oopsed off, that won't be useful, at least not for me.

Like I said, 7000 lines of diff between the 3.19 generic kernel config and your 4.1.0 optimized kernel config.  It doesn't take that long to compile the generic kernel.

**Comment by raphael** [comment]
I actually find a significant performance difference when using the proper config. For example `GENERIC_CPU=y` (that the generic config uses) vs. `MCORE2=y` (that this repo config uses) makes a big difference. I'm also not a big fan of compiling in support for all kinds of things that will just never get used (ATI or nvidia video cards, AMD CPU support, creative sound cards just to name a few). I'm happy tweaking the config to add support for things it is clearly missing though.

**Comment by recri** [comment]
The 4.1.3 kernel does not boot off a USB drive, the kernel packages in https://github.com/recri/linux-4.1-samus build/debian/*.deb boot off a USB drive, the build added one line to the config.

**Comment by luv2code** [comment]
FYI, mine boots with recri's kernel.

**Comment by raphael** [comment]
Nice, it's difficult for me to know which option is missing as I can't easily reproduce. If someone figures it out I'll happily add it.

**Comment by makerender** [comment]
Hi there, just tried both rapahel's and recri's kernels on the ubuntu based ElementaryOS install I have and neither booted for me. I also get the "Loading initial Ramdisk" hang on boot. I'm relatively new to kernels though so I'm not sure how to go about troubleshooting the issue.

**Comment by Seablade** [comment]
@makerender You need to manually build the kernel from recri's repo, and the config recri is referring to is actually in the generic-config branch, not the master branch, so make sure you check out that branch.  I did get it working after discovering that,however...

@recri Does your audio work?  I am running your kernel now, but I am having issues with audio, namely I get the following error via dmesg...

bdw-rt5677 bdw-rt5677: ASoC: CPU DAI System Pin not registered

         Seablade

**Comment by recri** [comment]
My audio works well enough that I successfully took a hangouts call in chrome this morning.  My headphones are too quiet and sometimes have reversed channels.

Sorry about hiding the generic kernel in a topic branch, the compiled packages were supposed to be in the branch, too, but I see I botched it.

**Comment by Seablade** [comment]
Very strange.  I wonder why I am having issues.

**Comment by Seablade** [comment]
@raphael Ok one difference between these kernels that will cause what I am seeing, as I just found out, is that XHCI is modularized in your build, and if you are booting off an external drive this doesn't work to well apparently as it isn't loaded fast enough I suspect.  So I would suggest XHCI at least 

CONFIG_USB_XHCI_HCD=m
CONFIG_USB_XHCI_PCI=m

Both be 'y' instead of 'm'.

That is a start I think, but that was discovered accidentally while trying to find a way to force USB2 speeds on the ports to test if that might be causing a problem with an audio interface I have.

             Seablade

**Comment by Seablade** [comment]
@recri Got it to work, the problem was one of the intel firmware files was expected to be in the /lib/firmware/intel subdirectory, but I had copied it with the rest of them over into /lib/firmware/

Still throwing a pin error, not the same one, but seems to be working at least.  Now to handle keybindings etc.  Hopefully I will get time sometime to sit down and do some comparisons between kernel configs in the future, but am at a funeral at the moment and will be out of town for the next month so it will be a while probably before I can do anything more detailed.

**Comment by raphael** [comment]
I've released a new version of the kernel (v4.1-9) that has built-in support for USB 1.1, 2.0 and 3.0. @Seablade could you give it a shot?

**Comment by Seablade** [comment]
Yea if I get a moment tomorrow I will, just pulled a later night than I would have liked to get some video work done for this funeral, so to tired to tonight, sorry.  I can always build it myself as well as needed, but curious to see if that might have been the only issue, but would be strange that it worked for some people and not others, as I don't know of to many boot processes that aren't doing similar things these days.

**Comment by raphael** [comment]
no rush, take your time.

**Comment by sprc** [comment]
I was able to boot this morning from a USB 3.0 stick with v4.1-9! Beautiful stuff. Kudos all around (and apologies for the red-herring at the beginning of the thread).

**Comment by recri** [comment]
I was able to boot off a Sandisk USB 3.0 thumb drive and a Lexar microsd card in a USB 3.0 adapter with  this latest kernel.  But returned to getting boot.log errors about kernel modules failing to load (those were missing parallel port modules last time I fixed it) and apparmor failing to start (because it isn't the default security policy as Ubuntu expects).

**Comment by makerender** [comment]
Hey @raphael, does this new release need to be manually built or can I dpkg them as per the instructions in the readme?

**Comment by recri** [comment]
I just pulled the master branch and installed build/debian/*.deb, no build required.

**Comment by raphael** [comment]
Yes, no build required. @recri do you know exactly which modules are missing? if so could you open a new issue? happy to add them. Also I'll change the default security policy to apparmor in the next build. I'm going to close this issue as the original problem is solved with the latest builds.
